//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureDBwithEntityDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp
    {
        public int empid { get; set; }
        public string empName { get; set; }
        public Nullable<decimal> empSalary { get; set; }
        public string empLocation { get; set; }
    }
}
